services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend.Dockerfile
    environment:
      DATABASE_URL: "postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/postgres?schema=public"
    ports:
      - "8032:8032" # Expose only the web part running on 8032
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:17.2-alpine3.21
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

  nginx:
      image: nginx:alpine
      container_name: nginx
      ports:
        - "443:443"  # Expose HTTPS on port 443
        - "80:80"    # Redirect HTTP to HTTPS
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro   # Use a custom NGINX config
        - ./ssl:/etc/nginx/ssl:ro  # Mount SSL certificates
      depends_on:
        - backend
      networks:
        - app_network

volumes:
  pgdata: {}

networks:
  app_network:
    driver: bridge
