services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend.Dockerfile
    environment:
      DATABASE_URL: "postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/postgres?schema=public"
    ports:
      - "8032:8032" # Expose only the web part running on 8032
    depends_on:
      - db

  db:
    image: postgres:17.2-alpine3.21
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
